import type { Application, Notification, Opportunity } from "../types";

export const skills = [
  "JavaScript","TypeScript","React","Node.js","Python","Java","C++","SQL","PostgreSQL","Git",
  "HTML","CSS","Tailwind CSS","REST APIs","DSA","DBMS","Operating Systems","Networking",
  "AWS","Docker","Kubernetes","System Design","Testing","Figma","Excel","Power BI",
  "Machine Learning","TensorFlow","Communication","Leadership","Problem Solving"
];


export const opportunities: Opportunity[] = [
  // ==================== JOBS & INTERNSHIPS ====================
  {
    id: "o1",
    title: "Frontend Developer Intern",
    company: "NovaTech Labs",
    type: "Internship",
    location: "Hyderabad, India",
    workMode: "Hybrid",
    compensation: "₹15,000/month",
    duration: "3 Months",
    skills: ["React", "JavaScript", "Git"],
    eligibility: "B.Tech / B.E. students",
    deadline: "2026-09-25",
    match: 87,
    description:
      "Build responsive product interfaces with React and TypeScript while working with a product engineering team.",
  },
  {
    id: "o2",
    title: "Software Engineer",
    company: "CloudSprint",
    type: "Job",
    location: "Bengaluru, India",
    workMode: "On-site",
    compensation: "₹8–12 LPA",
    skills: ["Java", "DSA", "SQL", "Git"],
    eligibility: "0–2 years experience",
    deadline: "2026-09-30",
    match: 79,
    description:
      "Join the platform team and build reliable backend services.",
  },
  {
    id: "o3",
    title: "Data Analyst Intern",
    company: "InsightWorks",
    type: "Internship",
    location: "Remote",
    workMode: "Remote",
    compensation: "₹20,000/month",
    duration: "4 Months",
    skills: ["Python", "SQL", "Power BI"],
    eligibility: "Students with analytics interest",
    deadline: "2026-09-20",
    match: 74,
    description:
      "Turn operational data into dashboards and actionable business insights.",
  },
  {
    id: "o4",
    title: "Cloud Engineering Graduate",
    company: "AeroStack",
    type: "Job",
    location: "Pune, India",
    workMode: "Hybrid",
    compensation: "₹9–14 LPA",
    skills: ["AWS", "Linux", "Docker", "Networking"],
    eligibility: "2026/2027 graduates",
    deadline: "2026-10-02",
    match: 61,
    description:
      "Work on cloud infrastructure, observability and deployment automation.",
  },
  {
    id: "o5",
    title: "AI/ML Intern",
    company: "VisionForge",
    type: "Internship",
    location: "Chennai, India",
    workMode: "Hybrid",
    compensation: "₹25,000/month",
    duration: "6 Months",
    skills: ["Python", "Machine Learning", "TensorFlow"],
    eligibility: "Students with ML projects",
    deadline: "2026-09-28",
    match: 68,
    description:
      "Prototype machine learning solutions and evaluate models with an applied AI team.",
  },
  {
    id: "o6",
    title: "React Native Intern",
    company: "MobilityOne",
    type: "Internship",
    location: "Remote",
    workMode: "Remote",
    compensation: "₹18,000/month",
    duration: "3 Months",
    skills: ["React", "JavaScript", "Git"],
    eligibility: "B.Tech students",
    deadline: "2026-09-18",
    match: 84,
    description:
      "Build cross-platform mobile experiences.",
  },
  {
    id: "o7",
    title: "Junior Backend Engineer",
    company: "DataMesh Systems",
    type: "Job",
    location: "Hyderabad, India",
    workMode: "Hybrid",
    compensation: "₹7–10 LPA",
    skills: ["Node.js", "SQL", "REST APIs", "Git"],
    eligibility: "Freshers welcome",
    deadline: "2026-10-05",
    match: 81,
    description:
      "Create APIs and data services for a growing B2B platform.",
  },
  {
    id: "o8",
    title: "Industry Training: Cloud Foundations",
    company: "AeroStack Academy",
    type: "Training",
    location: "Online",
    workMode: "Remote",
    compensation: "Free",
    duration: "6 Weeks",
    skills: ["AWS", "Networking", "Linux"],
    eligibility: "Students & faculty",
    deadline: "2026-09-15",
    match: 72,
    description:
      "Hands-on cloud foundations program with a completion certificate.",
  },
  {
    id: "o9",
    title: "Product Design Workshop",
    company: "DesignCircuit",
    type: "Workshop",
    location: "Online",
    workMode: "Remote",
    compensation: "₹999",
    duration: "2 Days",
    skills: ["Figma", "Communication"],
    eligibility: "All learners",
    deadline: "2026-09-12",
    match: 65,
    description:
      "Practical product design workshop from discovery to high-fidelity prototype.",
  },
  {
    id: "o10",
    title: "Full Stack Developer",
    company: "StackPilot",
    type: "Job",
    location: "Bengaluru, India",
    workMode: "Hybrid",
    compensation: "₹10–16 LPA",
    skills: ["React", "Node.js", "SQL", "TypeScript"],
    eligibility: "0–2 years experience",
    deadline: "2026-10-08",
    match: 82,
    description:
      "Own features end to end across frontend, backend and data layers.",
  },

  // ==================== RESEARCH ====================
  {
    id: "o11",
    title: "Research Collaboration: Generative AI",
    company: "OpenResearch Collective",
    type: "Research",
    location: "Remote",
    workMode: "Remote",
    compensation: "Research Collaboration",
    duration: "6 Months",
    skills: ["Python", "Machine Learning", "Research"],
    eligibility: "Faculty and research scholars",
    deadline: "2026-10-12",
    match: 86,
    description:
      "Collaborate on applied generative AI research, experimentation, academic documentation and publication preparation.",
  },
  {
    id: "o12",
    title: "Smart Campus Data Research",
    company: "FutureTech Research Centre",
    type: "Research",
    location: "Visakhapatnam, India",
    workMode: "Hybrid",
    compensation: "Research Partnership",
    duration: "4 Months",
    skills: ["Python", "Data Analytics", "Machine Learning"],
    eligibility: "Faculty and academic researchers",
    deadline: "2026-11-10",
    match: 82,
    description:
      "Study campus data patterns and develop data-driven solutions for improving educational environments.",
  },

  // ==================== FDPs & WORKSHOPS ====================
  {
    id: "o13",
    title: "Faculty Development Program: AI in Education",
    company: "EduInnovate Network",
    type: "FDP",
    location: "Online",
    workMode: "Remote",
    compensation: "Certificate",
    duration: "5 Days",
    skills: ["Machine Learning", "Communication"],
    eligibility: "Faculty and academicians",
    deadline: "2026-10-20",
    match: 91,
    description:
      "Explore practical applications of artificial intelligence in teaching, assessment and academic administration.",
  },
  {
    id: "o14",
    title: "Workshop on Academic Research Writing",
    company: "Academic Skills Centre",
    type: "Workshop",
    location: "Hyderabad, India",
    workMode: "On-site",
    compensation: "Certificate Included",
    duration: "2 Days",
    skills: ["Research", "Communication", "Problem Solving"],
    eligibility: "Faculty, scholars and educators",
    deadline: "2026-11-05",
    match: 85,
    description:
      "Learn literature review techniques, research paper structure, citations and publication planning.",
  },
  {
    id: "o15",
    title: "Advanced Cloud Computing FDP",
    company: "Cloud Learning Institute",
    type: "FDP",
    location: "Online",
    workMode: "Remote",
    compensation: "₹1,499",
    duration: "7 Days",
    skills: ["AWS", "Docker", "Kubernetes"],
    eligibility: "Faculty members and trainers",
    deadline: "2026-11-18",
    match: 78,
    description:
      "A practical development program covering cloud deployment, containerization and modern infrastructure.",
  },

  // ==================== MENTORSHIP ====================
  {
    id: "o16",
    title: "Industry Mentorship for Academic Leaders",
    company: "Industry Mentor Network",
    type: "Mentorship",
    location: "Remote",
    workMode: "Remote",
    compensation: "Mentorship Program",
    duration: "3 Months",
    skills: ["Leadership", "Communication"],
    eligibility: "Faculty members and academic coordinators",
    deadline: "2026-12-01",
    match: 88,
    description:
      "Receive guidance from industry professionals on leadership, academic-industry partnerships and professional development.",
  },
  {
    id: "o17",
    title: "Research Career Mentorship Program",
    company: "ScholarBridge",
    type: "Mentorship",
    location: "Online",
    workMode: "Remote",
    compensation: "Free",
    duration: "8 Weeks",
    skills: ["Research", "Problem Solving", "Communication"],
    eligibility: "Research scholars and early-career faculty",
    deadline: "2026-11-25",
    match: 83,
    description:
      "Connect with experienced researchers for advice on research planning, collaboration and academic career development.",
  },

  // ==================== FACULTY OPPORTUNITIES ====================
  {
    id: "o18",
    title: "Industry Guest Lecture Partnership",
    company: "Innovation Connect",
    type: "Faculty",
    location: "Hybrid",
    workMode: "Hybrid",
    compensation: "Professional Collaboration",
    duration: "1 Month",
    skills: ["Communication", "Leadership"],
    eligibility: "Faculty members and academic coordinators",
    deadline: "2026-11-20",
    match: 80,
    description:
      "Partner with industry professionals to organize guest lectures, expert sessions and academic-industry interactions.",
  },
  {
    id: "o19",
    title: "Academic Innovation Challenge",
    company: "Campus Innovation Forum",
    type: "Faculty",
    location: "Bengaluru, India",
    workMode: "Hybrid",
    compensation: "Innovation Grant Opportunity",
    duration: "3 Months",
    skills: ["Problem Solving", "Leadership", "Communication"],
    eligibility: "Faculty teams and academic institutions",
    deadline: "2026-12-15",
    match: 77,
    description:
      "Develop innovative solutions for improving student engagement, campus learning and institutional processes.",
  },

  // ==================== CONSULTANCY ====================
  {
    id: "o20",
    title: "Academic Curriculum Consultancy",
    company: "FutureSkills Consulting",
    type: "Consultancy",
    location: "Remote",
    workMode: "Remote",
    compensation: "Paid Consultancy",
    duration: "2 Months",
    skills: ["Communication", "Leadership", "Problem Solving"],
    eligibility: "Experienced faculty and subject experts",
    deadline: "2026-12-10",
    match: 89,
    description:
      "Support curriculum development, industry skill mapping and academic program improvement as a subject expert.",
  },
  {
    id: "o21",
    title: "Educational Technology Implementation Consultant",
    company: "Digital Campus Solutions",
    type: "Consultancy",
    location: "Hyderabad, India",
    workMode: "Hybrid",
    compensation: "Project-Based Payment",
    duration: "3 Months",
    skills: ["React", "SQL", "Communication"],
    eligibility: "Faculty with technology and implementation experience",
    deadline: "2026-12-20",
    match: 81,
    description:
      "Advise educational institutions on implementing digital learning platforms, student dashboards and technology-enabled workflows.",
  },
];