import { useMemo, useState } from 'react';
import { Download, Search, Bell, CheckCircle2, Building2, BriefcaseBusiness, GraduationCap, BarChart3, FileText, Settings as SettingsIcon, Eye, Users, Filter, ChevronDown } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { allUsers, getMyData, getOpportunities, updateProfile, markNotification } from '../services/store';
import { ProgressBar } from '../components/ProgressBar';

function Title({title,subtitle}:{title:string;subtitle:string}){return <div><h1 className="text-2xl font-black">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="card p-5"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="card p-8 text-center text-sm text-slate-500">{text}</div>}
function relevance(u:any,o:any){
 const p=`${u?.profile?.department||''} ${u?.profile?.expertise||''} ${u?.profile?.careerGoal||''} ${u?.profile?.preferredIndustrySectors||''}`.toLowerCase();
 const hay=`${o.title} ${o.description} ${o.company} ${o.skills.join(' ')}`.toLowerCase();
 const terms=p.split(/[\s,;/]+/).filter((x:string)=>x.length>2);
 const hits=terms.filter((x:string)=>hay.includes(x)).length;
 return Math.min(99,55+hits*7);
}

export function InstitutionDashboard(){
 const students=allUsers().filter((u:any)=>u.role==='student');
 const ops=getOpportunities();
 const assessed=students.filter((u:any)=>u.assessment);
 const applications=students.flatMap((u:any)=>(u.applications||[]));
 const placed=applications.filter((a:any)=>a.stage==='Selected').length;
 const internships=applications.filter((a:any)=>{const o=ops.find(x=>x.id===a.opportunityId);return o?.type==='Internship';});
 const partners=new Set(ops.map(o=>o.company)).size;
 const verified=students.filter((u:any)=>(u.profile?.currentSkills||[]).length>=3).length;
 const gaps=students.flatMap((u:any)=>u.assessment?.gaps||[]);
 const common=Object.entries(gaps.reduce((a:any,g:string)=>{a[g]=(a[g]||0)+1;return a},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,5);
 return <div className="space-y-6"><Title title="Institution Dashboard" subtitle="A single overview of student readiness, internships, placements, industry partnerships and skill gaps."/>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total Students" value={String(students.length)}/><Stat label="Verified Skills" value={String(verified)}/><Stat label="Internship Participation" value={String(internships.length)}/><Stat label="Placement Rate" value={students.length?`${Math.round(placed/students.length*100)}%`:'0%'}/></div>
  <div className="grid gap-5 lg:grid-cols-2"><div className="card p-6"><h2 className="font-bold">Skill-gap overview</h2>{common.length?common.map(([g,n]:any)=><div className="mt-4" key={g}><div className="mb-1 flex justify-between text-sm"><span>{g}</span><b>{n}</b></div><ProgressBar label="" value={Math.min(100,n/students.length*100)}/></div>):<p className="mt-4 text-sm text-slate-500">Skill gaps appear after students complete assessments.</p>}</div>
   <div className="card p-6"><h2 className="font-bold">Placement & industry snapshot</h2>{[['Placed students',placed],['Applications',applications.length],['Industry partnerships',partners],['Assessed students',assessed.length]].map(([x,n]:any)=><div className="mt-3 flex justify-between rounded-xl bg-slate-50 p-4" key={x}><span>{x}</span><b>{n}</b></div>)}</div></div>
  <div className="card p-6"><h2 className="font-bold">Recent activities</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[...applications.slice(0,3).map((a:any)=>`${a.role} application — ${a.stage}`),...ops.slice(0,3).map(o=>`New ${o.type.toLowerCase()} opportunity — ${o.title}`)].slice(0,6).map((x,i)=><div className="rounded-xl border border-slate-100 p-4 text-sm" key={i}><CheckCircle2 size={15} className="mb-2 text-emerald-500"/>{x}</div>)}{!applications.length&&!ops.length&&<p className="text-sm text-slate-500">No recent activities yet.</p>}</div></div>
  <div className="card p-6"><h2 className="font-bold">Important notifications</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-cyan-50 p-4 text-sm">Monitor new internships and placement drives.</div><div className="rounded-xl bg-amber-50 p-4 text-sm">Review students with outstanding skill gaps.</div><div className="rounded-xl bg-emerald-50 p-4 text-sm">Maintain current industry partnerships.</div></div></div>
 </div>
}

export function InstitutionStudents(){
 const [q,setQ]=useState(''); const [department,setDepartment]=useState('All'); const [selected,setSelected]=useState<any>(null);
 const students=allUsers().filter((u:any)=>u.role==='student'); const departments=['All',...Array.from(new Set(students.map((u:any)=>String(u.profile?.department||'Not specified'))))];
 const filtered=students.filter((u:any)=>`${u.name} ${u.email} ${u.profile?.department||''} ${(u.profile?.currentSkills||[]).join(' ')}`.toLowerCase().includes(q.toLowerCase())&&(department==='All'||String(u.profile?.department||'Not specified')===department));
 return <div className="space-y-6"><Title title="Students" subtitle="Search, filter and inspect student skills, learning, internships and placement information."/>
  <div className="card p-4 grid gap-3 md:grid-cols-[1fr_220px]"><div className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="input pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by name, email, department or skill…"/></div><select className="input" value={department} onChange={e=>setDepartment(e.target.value)}>{departments.map(d=><option key={d}>{d}</option>)}</select></div>
  <p className="text-sm text-slate-500">{filtered.length} student{filtered.length!==1?'s':''} found.</p>
  <div className="space-y-3">{filtered.map((u:any)=><div className="card flex flex-wrap items-center justify-between gap-4 p-5" key={u.id}><div><b>{u.name}</b><p className="text-sm text-slate-500">{u.email} · {u.profile?.department||'Department not specified'} · {u.profile?.desiredJobRole||u.profile?.careerGoal||'Career goal not set'}</p><div className="mt-2 flex flex-wrap gap-1">{(u.profile?.currentSkills||[]).slice(0,6).map((s:string)=><span className="badge bg-slate-100 text-slate-600" key={s}>{s}</span>)}</div></div><button className="btn-secondary" onClick={()=>setSelected(u)}><Eye size={15}/> View details</button></div>)}{!filtered.length&&<Empty text="No students match the current search and filter."/>}</div>
  {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-5" onClick={()=>setSelected(null)}><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6 shadow-xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><h2 className="text-xl font-black">{selected.name}</h2><p className="text-sm text-slate-500">{selected.email}</p></div><button className="btn-secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Department',selected.profile?.department],['College',selected.profile?.college],['Career Goal',selected.profile?.careerGoal],['Desired Job Role',selected.profile?.desiredJobRole],['Graduation Year',selected.profile?.graduationYear],['Assessment Score',selected.assessment?`${selected.assessment.overall}%`:'Not assessed']].map(([k,v]:any)=><div className="rounded-xl bg-slate-50 p-4" key={k}><p className="text-xs text-slate-400">{k}</p><p className="mt-1 font-semibold">{v||'Not specified'}</p></div>)}</div><InfoList title="Skills" items={selected.profile?.currentSkills||[]}/><InfoList title="Certifications" items={selected.portfolio?.certifications||[]}/><InfoList title="Projects" items={selected.portfolio?.projects||[]}/><InfoList title="Internships" items={selected.portfolio?.internships||[]}/><div className="mt-4"><h3 className="font-bold">Placement information</h3><p className="mt-2 text-sm text-slate-500">{(selected.applications||[]).filter((a:any)=>a.stage==='Selected').length?'Selected for placement':'No selected placement application yet.'}</p></div></div></div>}
 </div>
}
function InfoList({title,items}:{title:string;items:string[]}){return <div className="mt-5"><h3 className="font-bold">{title}</h3><div className="mt-2 flex flex-wrap gap-2">{items.length?items.map(x=><span className="badge bg-cyan-50 text-cyan-700" key={x}>{x}</span>):<span className="text-sm text-slate-400">None recorded</span>}</div></div>}

export function InstitutionSkillAnalysis(){
 const students=allUsers().filter((u:any)=>u.role==='student'); const ops=getOpportunities();
 const skillCounts:any={}; const gapCounts:any={}; students.forEach((u:any)=>{(u.profile?.currentSkills||[]).forEach((s:string)=>skillCounts[s]=(skillCounts[s]||0)+1);(u.assessment?.gaps||[]).forEach((g:string)=>gapCounts[g]=(gapCounts[g]||0)+1)});
 const common=Object.entries(skillCounts).sort((a:any,b:any)=>b[1]-a[1]); const gaps=Object.entries(gapCounts).sort((a:any,b:any)=>b[1]-a[1]); const demand:any={};ops.forEach(o=>o.skills.forEach(s=>demand[s]=(demand[s]||0)+1));const demandList=Object.entries(demand).sort((a:any,b:any)=>b[1]-a[1]);
 return <div className="space-y-6"><Title title="Skill Analysis" subtitle="Institution-wide skill distribution, skill gaps, in-demand skills and students needing improvement."/>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Students analysed" value={String(students.length)}/><Stat label="Unique skills" value={String(common.length)}/><Stat label="Tracked skill gaps" value={String(gaps.length)}/><Stat label="In-demand skills" value={String(demandList.length)}/></div>
  <div className="grid gap-5 lg:grid-cols-2"><SkillTable title="Most common skills" entries={common}/><SkillTable title="Students needing improvement" entries={gaps}/></div>
  <div className="grid gap-5 lg:grid-cols-2"><SkillTable title="In-demand skills from opportunities" entries={demandList}/><div className="card p-6"><h2 className="font-bold">Department / branch analysis</h2>{Object.entries(students.reduce((a:any,u:any)=>{const d=String(u.profile?.department||'Not specified');a[d]=(a[d]||0)+1;return a},{})).map(([d,n]:any)=><div className="mt-3 flex justify-between rounded-xl bg-slate-50 p-3 text-sm" key={d}><span>{d}</span><b>{n} students</b></div>)}{!students.length&&<p className="mt-3 text-sm text-slate-500">No student data available.</p>}</div></div>
 </div>
}
function SkillTable({title,entries}:{title:string;entries:any[]}){return <div className="card p-6"><h2 className="font-bold">{title}</h2><div className="mt-4 space-y-3">{entries.slice(0,8).map(([name,count]:any)=><div className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm" key={name}><span>{name}</span><b>{count}</b></div>)}{!entries.length&&<p className="text-sm text-slate-500">No data available yet.</p>}</div></div>}

export function InstitutionInternships(){
 const students=allUsers().filter((u:any)=>u.role==='student'); const ops=getOpportunities().filter(o=>o.type==='Internship');const apps=students.flatMap((u:any)=>(u.applications||[]).map((a:any)=>({...a,student:u.name}))).filter((a:any)=>ops.some(o=>o.id===a.opportunityId));
 return <div className="space-y-6"><Title title="Internships" subtitle="Internship opportunities, participation, applications and completion status."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Opportunities" value={String(ops.length)}/><Stat label="Applications" value={String(apps.length)}/><Stat label="Ongoing / selected" value={String(apps.filter((a:any)=>['AI Shortlisted','Interview','Selected'].includes(a.stage)).length)}/><Stat label="Completed" value={String(students.flatMap((u:any)=>u.portfolio?.internships||[]).length)}/></div><div className="grid gap-4 lg:grid-cols-2">{ops.map(o=><div className="card p-5" key={o.id}><span className="badge bg-cyan-50 text-cyan-700">Internship</span><h2 className="mt-3 font-bold">{o.title}</h2><p className="text-sm text-slate-500">{o.company} · {o.location}</p><p className="mt-3 text-sm text-slate-600">{o.description}</p><div className="mt-4 flex justify-between text-xs text-slate-400"><span>{o.skills.join(', ')}</span><span>{o.compensation}</span></div></div>)}</div>{!ops.length&&<Empty text="No internship opportunities are available yet."/>}<div className="card p-6"><h2 className="font-bold">Student internship status</h2>{apps.slice(0,10).map((a:any)=><div className="mt-3 flex justify-between rounded-xl bg-slate-50 p-3 text-sm" key={a.id}><span>{a.student} · {a.role}</span><b>{a.stage}</b></div>)}{!apps.length&&<p className="mt-3 text-sm text-slate-500">No internship applications yet.</p>}</div></div>
}

export function InstitutionPlacements(){
 const students=allUsers().filter((u:any)=>u.role==='student');const apps=students.flatMap((u:any)=>(u.applications||[]).map((a:any)=>({...a,student:u.name})));const selected=apps.filter((a:any)=>a.stage==='Selected');const companies=Array.from(new Set(selected.map((a:any)=>a.company)));
 return <div className="space-y-6"><Title title="Placements" subtitle="Placement drives, recruiters, student status and placement statistics."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Students placed" value={String(selected.length)}/><Stat label="Students not yet placed" value={String(Math.max(0,students.length-selected.length))}/><Stat label="Recruiters" value={String(companies.length)}/><Stat label="Placement rate" value={students.length?`${Math.round(selected.length/students.length*100)}%`:'0%'}/></div><div className="grid gap-5 lg:grid-cols-2"><div className="card p-6"><h2 className="font-bold">Placement status</h2>{students.map((u:any)=>{const a=(u.applications||[]).find((x:any)=>x.stage==='Selected');return <div className="mt-3 flex justify-between rounded-xl bg-slate-50 p-3 text-sm" key={u.id}><span>{u.name}</span><b>{a?`Placed — ${a.company}`:'Not placed'}</b></div>})}</div><div className="card p-6"><h2 className="font-bold">Placement drives & recruiters</h2>{companies.map(c=><div className="mt-3 flex justify-between rounded-xl bg-slate-50 p-3 text-sm" key={c}><span>{c}</span><b>Recruiter</b></div>)}{!companies.length&&<p className="mt-3 text-sm text-slate-500">Recruiter information will appear when students are selected.</p>}</div></div></div>
}

export function InstitutionPartners(){
 const ops=getOpportunities();const names=Array.from(new Set(ops.map(o=>o.company)));const [selected,setSelected]=useState<string|null>(null);
 return <div className="space-y-6"><Title title="Industry Partners" subtitle="Partner companies, collaboration details and linked internship or placement opportunities."/><div className="grid gap-4 md:grid-cols-2">{names.map(name=>{const po=ops.filter(o=>o.company===name);return <div className="card p-5" key={name}><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-50"><Building2 className="text-cyan-600"/></div><div><h2 className="font-bold">{name}</h2><p className="text-sm text-slate-500">{po.length} associated opportunities</p></div></div><button className="btn-secondary" onClick={()=>setSelected(selected===name?null:name)}>{selected===name?'Hide':'Details'}</button></div>{selected===name&&<div className="mt-4 border-t pt-4 text-sm"><p className="font-semibold">Collaboration information</p><p className="mt-1 text-slate-500">This partner currently has opportunities connected to the institution marketplace.</p><p className="mt-3 font-semibold">Associated opportunities</p>{po.map(o=><div className="mt-2 rounded-xl bg-slate-50 p-3" key={o.id}>{o.title} · {o.type}</div>)}</div>}</div>})}</div>{!names.length&&<Empty text="No industry partners are available yet."/>}</div>
}

export function InstitutionReports(){
 const [message,setMessage]=useState('');const students=allUsers().filter((u:any)=>u.role==='student');const apps=students.flatMap((u:any)=>u.applications||[]);
 const report=(name:string)=>{const rows=[['EduLyra Institution Report',name],['Generated',new Date().toLocaleString()],['Students',students.length],['Applications',apps.length],['Selected',apps.filter((a:any)=>a.stage==='Selected').length]];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`EduLyra-${name.replace(/\s+/g,'-')}.csv`;a.click();URL.revokeObjectURL(url);setMessage(`${name} generated and downloaded.`)};
 return <div className="space-y-6"><Title title="Reports" subtitle="Generate and export institution performance reports."/><div className="grid gap-4 md:grid-cols-2">{['Student Skill Report','Internship Report','Placement Report','Industry Partnership Report','Overall Institution Performance'].map(name=><div className="card flex items-center justify-between gap-4 p-5" key={name}><div><FileText size={20} className="text-cyan-600"/><h2 className="mt-2 font-bold">{name}</h2><p className="mt-1 text-xs text-slate-500">View and export the current report data.</p></div><button className="btn-primary" onClick={()=>report(name)}><Download size={15}/> Export</button></div>)}</div>{message&&<div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}</div>
}

export function InstitutionNotifications(){
 const user:any=getMyData();const [refresh,setRefresh]=useState(0);const generated=[{id:'n1',title:'Internship opportunities updated',body:`${getOpportunities().filter(o=>o.type==='Internship').length} internship opportunities are currently available.`,time:'Current',read:false},{id:'n2',title:'Placement monitoring',body:'Review selected, interview and pending student applications in Placements.',time:'Current',read:false},{id:'n3',title:'Skill analysis available',body:'Review common skills and assessment-based skill gaps.',time:'Current',read:false}];const ns=user?.notifications?.length?user.notifications:generated;
 return <div className="space-y-6"><Title title="Notifications" subtitle="Institution updates, internship announcements, placement alerts and student-related activities."/><div className="space-y-3">{ns.map((n:any)=><button className={`card flex w-full gap-4 p-5 text-left ${n.read?'opacity-60':''}`} key={n.id} onClick={()=>{if(user?.notifications?.some((x:any)=>x.id===n.id))markNotification(n.id);setRefresh(refresh+1)}}><Bell className="shrink-0 text-cyan-600"/><div><b>{n.title}</b><p className="mt-1 text-sm text-slate-500">{n.body}</p><p className="mt-2 text-xs text-slate-400">{n.time} · {n.read?'Read':'Unread'}</p></div></button>)}</div></div>
}

export function InstitutionSettings(){
 const u:any=getMyData();const [name,setName]=useState(u?.name||'');const [institution,setInstitution]=useState(u?.profile?.institutionName||'');const [saved,setSaved]=useState(false);
 const save=()=>{updateProfile({displayName:name,institutionName:institution});setSaved(true)};
 return <div className="mx-auto max-w-2xl space-y-6"><Title title="Institution Settings" subtitle="Manage institution profile, account information, notifications and security preferences."/><div className="card p-6 space-y-4"><div><label className="label">Administrator name</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="label">Institution name</label><input className="input" value={institution} onChange={e=>setInstitution(e.target.value)}/></div><div className="rounded-xl bg-slate-50 p-4 text-sm"><b>Account information</b><p className="mt-1 text-slate-500">{u?.email}</p></div><div className="rounded-xl bg-slate-50 p-4 text-sm"><b>Notification preferences</b><p className="mt-1 text-slate-500">Institution alerts are shown in Notifications.</p></div><div className="rounded-xl bg-slate-50 p-4 text-sm"><b>Password / security</b><p className="mt-1 text-slate-500">Use the existing account authentication flow to manage access securely.</p></div><button className="btn-primary" onClick={save}><SettingsIcon size={15}/> Save institution settings</button>{saved&&<p className="text-sm text-emerald-700">Institution settings saved successfully.</p>}</div></div>
}
